### ISSUE TITLE
A1 model

### ISSUE THREAD

**Issue by cesonic** [Praful22/A1-unitree-MPC-TrajectoryOptimization#1]
I am in need of the A1 model. Could you provide the file in the picture? If possible, thank you very much!

<img width="591" alt="50a146f50978c94e0c8e21133d4f700" src="https://github.com/Praful22/A1-unitree-Quadrupedal-robot/assets/42774222/3641b7fe-b447-4b54-8958-402f2282292a">

**Comment by Praful22** [comment]
Hello @cesonic, thank you for pointing this out. I have uploaded the a1_description folder. Please provide me an update if this works. Please don't hesitate to let me know if you run into any issues in the future! Happy learning!
[a1_description](https://github.com/Praful22/A1-unitree-Quadrupedal-robot/tree/main/a1_description)

**Comment by Praful22** [comment]
Since I didn't receive any update on this. I am going to assume the issue has been resolved and close this issue.

**Comment by cesonic** [comment]
> Since I didn't receive any update on this. I am going to assume the issue has been resolved and close this issue.

I'm so sorry for forgetting to reply promptly. My problem has been resolved. Thank you a lot!
